Neos:
  Flow:
    mvc:
      routes:
        'Networkteam.Neos.Shariff':
          position: 'before Neos.Neos'
    reflection:
      ignoredTags:
        unstable: true
  Neos:
    fusion:
      autoInclude:
        Networkteam.Neos.Shariff: true

Networkteam:
  Neos:
    Shariff:
      frontend:
        theme: standard
        orientation: horizontal
        language: en
      options:
        domain: null
        cache:
          ttl: 3600
        services:
#          - Facebook
#          - GooglePlus
#          - Twitter
#          - LinkedIn
#          - Reddit
#          - StumbleUpon
#          - Flattr
#          - Pinterest
#          - Xing
